name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Prettify code
      uses: jorenbroekema/prettier_action@fix/commit
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md}
        same_commit: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}